name: Deploy to Server

on:
  push:
    branches:
      - master   # run only on master push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Upload only changed files via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          local_path: "./"
          remote_path: "/var/www/research_and_glance"
          delete_remote_files: false
          sftpArgs: "-rpq"   # only changed files, compress transfer

      - name: Install deps & restart with PM2 (SSH)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            cd /var/www/research_and_glance
            npm install --production
            pm2 delete research_and_glance || true
            pm2 start server.js --name "research_and_glance"
            pm2 save
